AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'lambda-dynamo

  Sample SAM Template for lambda-dynamo

  '
Globals:
  Function:
    Timeout: 3
Resources:
  getUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://random-bucket-317/0c4cc33d677da912ac62e76665e0938c
      Handler: getUsers.handler
      Runtime: nodejs8.10
  postUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://random-bucket-317/0c4cc33d677da912ac62e76665e0938c
      Handler: app.handler
      Runtime: nodejs8.10
